{
	"version": 1591812244,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/colissions-sheet0.png",
		"images/coca-sheet0.png",
		"images/corona-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/cocona-sheet0.png",
		"images/fondo-sheet0.png",
		"images/fondo2-sheet0.png",
		"images/fondo3-sheet0.png",
		"images/fondo4-sheet0.png",
		"images/cocola_landcopy-sheet0.png",
		"images/cocola_fondo-sheet0.png",
		"images/tiledbackground.png",
		"images/cocola_health-sheet0.png",
		"images/cocola-sheet0.png",
		"images/jumpthrow-sheet0.png",
		"images/papel-sheet0.png",
		"images/cocola_papel-sheet0.png",
		"images/coronaspawnnormal-sheet0.png",
		"images/dead-sheet0.png",
		"images/menu-sheet0.png",
		"images/play-sheet0.png",
		"images/exit-sheet0.png",
		"images/menu_menu-sheet0.png",
		"images/corona2-sheet0.png",
		"images/stopcorona-sheet0.png",
		"images/portal-sheet0.png",
		"images/subida-sheet0.png",
		"images/bajada-sheet0.png",
		"images/sprite-sheet0.png",
		"images/stophorizontal-sheet0.png",
		"images/horizontal-sheet0.png",
		"images/coronaspawnrojo-sheet0.png",
		"images/cocola_fondo02copy-sheet0.png",
		"images/coronaspawnvertical-sheet0.png",
		"images/niveluno-sheet0.png",
		"images/tutorial-sheet0.png",
		"images/flechita-sheet0.png",
		"media/golpea enemigo.m4a",
		"media/golpea enemigo.ogg",
		"media/papel.m4a",
		"media/papel.ogg",
		"media/acepta.m4a",
		"media/acepta.ogg",
		"media/click.ogg",
		"media/comienza juego termina.ogg",
		"media/morir.m4a",
		"media/morir.ogg",
		"media/musicafondo menu level.m4a",
		"media/musicafondo menu level.ogg",
		"media/salto.m4a",
		"media/salto.ogg",
		"media/subevida.m4a",
		"media/subevida.ogg",
		"media/disparo.m4a",
		"media/disparo.ogg",
		"media/corona.m4a",
		"media/corona.ogg",
		"media/musica fondo mystical_pixels.m4a",
		"media/musica fondo mystical_pixels.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}